type CountryType = {
	name: string;
	code: string;
	iso: string;
	flag: string;
	mask: string | string[];
};

const countries: CountryType[] = [
	{
		name: "Afghanistan",
		code: "+93",
		iso: "AF",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/af.svg",
		mask: "__-___-____",
	},
	{
		name: "Aland Islands",
		code: "+358",
		iso: "AX",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ax.svg",
		mask: "(___) ___-__-__",
	},
	{
		name: "Albania",
		code: "+355",
		iso: "AL",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/al.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Algeria",
		code: "+213",
		iso: "DZ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/dz.svg",
		mask: "__-___-____",
	},
	{
		name: "American Samoa",
		code: "+1",
		iso: "AS",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/as.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Andorra",
		code: "+376",
		iso: "AD",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ad.svg",
		mask: "___-___",
	},
	{
		name: "Angola",
		code: "+244",
		iso: "AO",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ao.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Anguilla",
		code: "+1",
		iso: "AI",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ai.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Antarctica",
		code: "+672",
		iso: "AQ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/aq.svg",
		mask: "___-___",
	},
	{
		name: "Antigua and Barbuda",
		code: "+1",
		iso: "AG",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ag.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Argentina",
		code: "+54",
		iso: "AR",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ar.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Armenia",
		code: "+374",
		iso: "AM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/am.svg",
		mask: "__-___-___",
	},
	{
		name: "Aruba",
		code: "+297",
		iso: "AW",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/aw.svg",
		mask: "___-____",
	},
	{
		name: "Ascension Island",
		code: "+247",
		iso: "AC",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sh.svg",
		mask: "____",
	},
	{
		name: "Australia",
		code: "+61",
		iso: "AU",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/au.svg",
		mask: "_-____-____",
	},
	{
		name: "Austria",
		code: "+43",
		iso: "AT",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/at.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Azerbaijan",
		code: "+994",
		iso: "AZ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/az.svg",
		mask: "__-___-__-__",
	},
	{
		name: "Bahamas",
		code: "+1",
		iso: "BS",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bs.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Bahrain",
		code: "+973",
		iso: "BH",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bh.svg",
		mask: "____-____",
	},
	{
		name: "Bangladesh",
		code: "+880",
		iso: "BD",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bd.svg",
		mask: "____-______",
	},
	{
		name: "Barbados",
		code: "+1",
		iso: "BB",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bb.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Belarus",
		code: "+375",
		iso: "BY",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/by.svg",
		mask: "(__) ___-__-__",
	},
	{
		name: "Belgium",
		code: "+32",
		iso: "BE",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/be.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Belize",
		code: "+501",
		iso: "BZ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bz.svg",
		mask: "___-____",
	},
	{
		name: "Benin",
		code: "+229",
		iso: "BJ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bj.svg",
		mask: "__-__-____",
	},
	{
		name: "Bermuda",
		code: "+1",
		iso: "BM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bm.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Bhutan",
		code: "+975",
		iso: "BT",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bt.svg",
		mask: "_-___-___",
	},
	{
		name: "Bolivia",
		code: "+591",
		iso: "BO",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bo.svg",
		mask: "_-___-____",
	},
	{
		name: "Bosnia and Herzegovina",
		code: "+387",
		iso: "BA",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ba.svg",
		mask: "__-_____",
	},
	{
		name: "Botswana",
		code: "+267",
		iso: "BW",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bw.svg",
		mask: "__-___-___",
	},
	{
		name: "Brasil",
		code: "+55",
		iso: "BR",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/br.svg",
		mask: ["(__) _____-____", "(__) ____-____"],
	},
	{
		name: "British Indian Ocean Territory",
		code: "+246",
		iso: "IO",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/io.svg",
		mask: "___-____",
	},
	{
		name: "Brunei Darussalam",
		code: "+673",
		iso: "BN",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bn.svg",
		mask: "___-____",
	},
	{
		name: "Bulgaria",
		code: "+359",
		iso: "BG",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bg.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Burkina Faso",
		code: "+226",
		iso: "BF",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bf.svg",
		mask: "__-__-____",
	},
	{
		name: "Burundi",
		code: "+257",
		iso: "BI",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bi.svg",
		mask: "__-__-____",
	},
	{
		name: "Cambodia",
		code: "+855",
		iso: "KH",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/kh.svg",
		mask: "__-___-___",
	},
	{
		name: "Cameroon",
		code: "+237",
		iso: "CM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/cm.svg",
		mask: "____-____",
	},
	{
		name: "Canada",
		code: "+1",
		iso: "CA",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ca.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Cape Verde",
		code: "+238",
		iso: "CV",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/cv.svg",
		mask: "(___) __-__",
	},
	{
		name: "Cayman Islands",
		code: "+1",
		iso: "KY",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ky.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Central African Republic",
		code: "+236",
		iso: "CF",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/cf.svg",
		mask: "__-__-____",
	},
	{
		name: "Chad",
		code: "+235",
		iso: "TD",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/td.svg",
		mask: "__-__-__-__",
	},
	{
		name: "Chile",
		code: "+56",
		iso: "CL",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/cl.svg",
		mask: "_-____-____",
	},
	{
		name: "China",
		code: "+86",
		iso: "CN",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/cn.svg",
		mask: "__-_____-_____",
	},
	{
		name: "Christmas Island",
		code: "+61",
		iso: "CX",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/cx.svg",
		mask: "_-____-____",
	},
	{
		name: "Cocos (Keeling) Islands",
		code: "+61",
		iso: "CC",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/cc.svg",
		mask: "_-____-____",
	},
	{
		name: "Colombia",
		code: "+57",
		iso: "CO",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/co.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Comoros",
		code: "+269",
		iso: "KM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/km.svg",
		mask: "__-_____",
	},
	{
		name: "Congo",
		code: "+242",
		iso: "CG",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/cg.svg",
		mask: "__-_____",
	},
	{
		name: "Cook Islands",
		code: "+682",
		iso: "CK",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ck.svg",
		mask: "__-___",
	},
	{
		name: "Costa Rica",
		code: "+506",
		iso: "CR",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/cr.svg",
		mask: "____-____",
	},
	{
		name: "Croatia",
		code: "+385",
		iso: "HR",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/hr.svg",
		mask: "__-___-___",
	},
	{
		name: "Cuba",
		code: "+53",
		iso: "CU",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/cu.svg",
		mask: "_-___-____",
	},
	{
		name: "Cyprus",
		code: "+357",
		iso: "CY",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/cy.svg",
		mask: "__-___-___",
	},
	{
		name: "Czech Republic",
		code: "+420",
		iso: "CZ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/cz.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Democratic Republic of the Congo",
		code: "+243",
		iso: "CD",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/cd.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Denmark",
		code: "+45",
		iso: "DK",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/dk.svg",
		mask: "__-__-__-__",
	},
	{
		name: "Djibouti",
		code: "+253",
		iso: "DJ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/dj.svg",
		mask: "__-__-__-__",
	},
	{
		name: "Dominica",
		code: "+1",
		iso: "DM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/dm.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Dominican Republic",
		code: "+1",
		iso: "DO",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/do.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Ecuador",
		code: "+593",
		iso: "EC",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ec.svg",
		mask: "__-___-____",
	},
	{
		name: "Egypt",
		code: "+20",
		iso: "EG",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/eg.svg",
		mask: "(___) ___-____",
	},
	{
		name: "El Salvador",
		code: "+503",
		iso: "SV",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sv.svg",
		mask: "__-__-____",
	},
	{
		name: "Equatorial Guinea",
		code: "+240",
		iso: "GQ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gq.svg",
		mask: "__-___-____",
	},
	{
		name: "Eritrea",
		code: "+291",
		iso: "ER",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/er.svg",
		mask: "_-___-___",
	},
	{
		name: "Estonia",
		code: "+372",
		iso: "EE",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ee.svg",
		mask: "____-____",
	},
	{
		name: "Eswatini",
		code: "+268",
		iso: "SZ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sz.svg",
		mask: "__-__-____",
	},
	{
		name: "Ethiopia",
		code: "+251",
		iso: "ET",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/et.svg",
		mask: "__-___-____",
	},
	{
		name: "Falkland Islands (Malvinas)",
		code: "+500",
		iso: "FK",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/fk.svg",
		mask: "_____",
	},
	{
		name: "Faroe Islands",
		code: "+298",
		iso: "FO",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/fo.svg",
		mask: "__ __ __",
	},
	{
		name: "Fiji",
		code: "+679",
		iso: "FJ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/fj.svg",
		mask: "__-_____",
	},
	{
		name: "Finland",
		code: "+358",
		iso: "FI",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/fi.svg",
		mask: "__ ___ ____",
	},
	{
		name: "France",
		code: "+33",
		iso: "FR",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/fr.svg",
		mask: "_ __ __ __ __",
	},
	{
		name: "French Guiana",
		code: "+594",
		iso: "GF",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gf.svg",
		mask: "___ __ __ __",
	},
	{
		name: "French Polynesia",
		code: "+689",
		iso: "PF",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/pf.svg",
		mask: "__ __ __ __",
	},
	{
		name: "Gabon",
		code: "+241",
		iso: "GA",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ga.svg",
		mask: "_ __ __ __",
	},
	{
		name: "Gambia",
		code: "+220",
		iso: "GM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gm.svg",
		mask: "___ ____",
	},
	{
		name: "Georgia",
		code: "+995",
		iso: "GE",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ge.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Germany",
		code: "+49",
		iso: "DE",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/de.svg",
		mask: "(_____) __-____",
	},
	{
		name: "Ghana",
		code: "+233",
		iso: "GH",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gh.svg",
		mask: "___ ___ ____",
	},
	{
		name: "Gibraltar",
		code: "+350",
		iso: "GI",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gi.svg",
		mask: "___-_____",
	},
	{
		name: "Greece",
		code: "+30",
		iso: "GR",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gr.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Greenland",
		code: "+299",
		iso: "GL",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gl.svg",
		mask: "__-__-__",
	},
	{
		name: "Grenada",
		code: "+1",
		iso: "GD",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gd.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Guadeloupe",
		code: "+590",
		iso: "GP",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gp.svg",
		mask: "___ __ __ __",
	},
	{
		name: "Guam",
		code: "+1",
		iso: "GU",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gu.svg",
		mask: "___ ___ ____",
	},
	{
		name: "Guatemala",
		code: "+502",
		iso: "GT",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gt.svg",
		mask: "_-___-____",
	},
	{
		name: "Guernsey",
		code: "+44",
		iso: "GG",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gg.svg",
		mask: "(____) ______",
	},
	{
		name: "Guinea",
		code: "+224",
		iso: "GN",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gn.svg",
		mask: "__-___-___",
	},
	{
		name: "Guinea-Bissau",
		code: "+245",
		iso: "GW",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gw.svg",
		mask: "_-______",
	},
	{
		name: "Guyana",
		code: "+592",
		iso: "GY",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gy.svg",
		mask: "___-____",
	},
	{
		name: "Haiti",
		code: "+509",
		iso: "HT",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ht.svg",
		mask: "__-__-____",
	},
	{
		name: "Holy See (Vatican City State)",
		code: "+39",
		iso: "VA",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/va.svg",
		mask: "__ ________",
	},
	{
		name: "Honduras",
		code: "+504",
		iso: "HN",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/hn.svg",
		mask: "____-____",
	},
	{
		name: "Hong Kong",
		code: "+852",
		iso: "HK",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/hk.svg",
		mask: "____-____",
	},
	{
		name: "Hungary",
		code: "+36",
		iso: "HU",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/hu.svg",
		mask: "__ ___ ____",
	},
	{
		name: "Iceland",
		code: "+354",
		iso: "IS",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/is.svg",
		mask: "___-____",
	},
	{
		name: "India",
		code: "+91",
		iso: "IN",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/in.svg",
		mask: "(____) ___-___",
	},
	{
		name: "Indonesia",
		code: "+62",
		iso: "ID",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/id.svg",
		mask: "(___) ___-__-___",
	},
	{
		name: "Iran",
		code: "+98",
		iso: "IR",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ir.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Iraq",
		code: "+964",
		iso: "IQ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/iq.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Ireland",
		code: "+353",
		iso: "IE",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ie.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Isle of Man",
		code: "+44",
		iso: "IM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/im.svg",
		mask: "(____) ______",
	},
	{
		name: "Israel",
		code: "+972",
		iso: "IL",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/il.svg",
		mask: "__-___-____",
	},
	{
		name: "Italy",
		code: "+39",
		iso: "IT",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/it.svg",
		mask: "(___) ____-___",
	},
	{
		name: "Ivory Coast / Cote d'Ivoire",
		code: "+225",
		iso: "CI",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ci.svg",
		mask: "__-___-___",
	},
	{
		name: "Jamaica",
		code: "+1",
		iso: "JM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/jm.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Japan",
		code: "+81",
		iso: "JP",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/jp.svg",
		mask: "__-____-____",
	},
	{
		name: "Jersey",
		code: "+44",
		iso: "JE",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/je.svg",
		mask: "(____) ____-______",
	},
	{
		name: "Jordan",
		code: "+962",
		iso: "JO",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/jo.svg",
		mask: "_-____-____",
	},
	{
		name: "Kazakhstan",
		code: "+77",
		iso: "KZ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/kz.svg",
		mask: "(_____) _ __ __",
	},
	{
		name: "Kenya",
		code: "+254",
		iso: "KE",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ke.svg",
		mask: "___-______",
	},
	{
		name: "Kiribati",
		code: "+686",
		iso: "KI",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ki.svg",
		mask: "__-___",
	},
	{
		name: "Korea, Democratic People's Republic of Korea",
		code: "+850",
		iso: "KP",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/kp.svg",
		mask: "____-_____________",
	},
	{
		name: "Korea, Republic of South Korea",
		code: "+82",
		iso: "KR",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/kr.svg",
		mask: "__-___-____",
	},
	{
		name: "Kosovo",
		code: "+383",
		iso: "XK",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/xk.svg",
		mask: "___-___-___",
	},
	{
		name: "Kuwait",
		code: "+965",
		iso: "KW",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/kw.svg",
		mask: "____-____",
	},
	{
		name: "Kyrgyzstan",
		code: "+996",
		iso: "KG",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/kg.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Laos",
		code: "+856",
		iso: "LA",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/la.svg",
		mask: "(____) ___-___",
	},
	{
		name: "Latvia",
		code: "+371",
		iso: "LV",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/lv.svg",
		mask: "__-___-___",
	},
	{
		name: "Lebanon",
		code: "+961",
		iso: "LB",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/lb.svg",
		mask: "__-___-___",
	},
	{
		name: "Lesotho",
		code: "+266",
		iso: "LS",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ls.svg",
		mask: "_-___-____",
	},
	{
		name: "Liberia",
		code: "+231",
		iso: "LR",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/lr.svg",
		mask: "__-___-___",
	},
	{
		name: "Libya",
		code: "+218",
		iso: "LY",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ly.svg",
		mask: "__-___-____",
	},
	{
		name: "Liechtenstein",
		code: "+423",
		iso: "LI",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/li.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Lithuania",
		code: "+370",
		iso: "LT",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/lt.svg",
		mask: "(___) __-___",
	},
	{
		name: "Luxembourg",
		code: "+352",
		iso: "LU",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/lu.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Macau",
		code: "+853",
		iso: "MO",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mo.svg",
		mask: "____-____",
	},
	{
		name: "Madagascar",
		code: "+261",
		iso: "MG",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mg.svg",
		mask: "__-__-_____",
	},
	{
		name: "Malawi",
		code: "+265",
		iso: "MW",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mw.svg",
		mask: "_-____-____",
	},
	{
		name: "Malaysia",
		code: "+60",
		iso: "MY",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/my.svg",
		mask: "__-___-____",
	},
	{
		name: "Maldives",
		code: "+960",
		iso: "MV",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mv.svg",
		mask: "___-____",
	},
	{
		name: "Mali",
		code: "+223",
		iso: "ML",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ml.svg",
		mask: "__-__-____",
	},
	{
		name: "Malta",
		code: "+356",
		iso: "MT",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mt.svg",
		mask: "____-____",
	},
	{
		name: "Marshall Islands",
		code: "+692",
		iso: "MH",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mh.svg",
		mask: "___-____",
	},
	{
		name: "Martinique",
		code: "+596",
		iso: "MQ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mq.svg",
		mask: "(___) __-__-__",
	},
	{
		name: "Mauritania",
		code: "+222",
		iso: "MR",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mr.svg",
		mask: "__-__-____",
	},
	{
		name: "Mauritius",
		code: "+230",
		iso: "MU",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mu.svg",
		mask: "___-____",
	},
	{
		name: "Mayotte",
		code: "+262",
		iso: "YT",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/yt.svg",
		mask: "_____-____",
	},
	{
		name: "Mexico",
		code: "+52",
		iso: "MX",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mx.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Micronesia, Federated States of Micronesia",
		code: "+691",
		iso: "FM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/fm.svg",
		mask: "___-____",
	},
	{
		name: "Moldova",
		code: "+373",
		iso: "MD",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/md.svg",
		mask: "____-____",
	},
	{
		name: "Monaco",
		code: "+377",
		iso: "MC",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mc.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Mongolia",
		code: "+976",
		iso: "MN",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mn.svg",
		mask: "__-__-____",
	},
	{
		name: "Montenegro",
		code: "+382",
		iso: "ME",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/me.svg",
		mask: "__-___-___",
	},
	{
		name: "Montserrat",
		code: "+1",
		iso: "MS",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ms.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Morocco",
		code: "+212",
		iso: "MA",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ma.svg",
		mask: "__-____-___",
	},
	{
		name: "Mozambique",
		code: "+258",
		iso: "MZ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mz.svg",
		mask: "__-___-___",
	},
	{
		name: "Myanmar",
		code: "+95",
		iso: "MM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mm.svg",
		mask: "__-___-___",
	},
	{
		name: "Namibia",
		code: "+264",
		iso: "NA",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/na.svg",
		mask: "__-___-____",
	},
	{
		name: "Nauru",
		code: "+674",
		iso: "NR",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/nr.svg",
		mask: "___-____",
	},
	{
		name: "Nepal",
		code: "+977",
		iso: "NP",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/np.svg",
		mask: "__-___-___",
	},
	{
		name: "Netherlands",
		code: "+31",
		iso: "NL",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/nl.svg",
		mask: "__-___-____",
	},
	{
		name: "New Caledonia",
		code: "+687",
		iso: "NC",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/nc.svg",
		mask: "__-____",
	},
	{
		name: "New Zealand",
		code: "+64",
		iso: "NZ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/nz.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Nicaragua",
		code: "+505",
		iso: "NI",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ni.svg",
		mask: "____-____",
	},
	{
		name: "Niger",
		code: "+227",
		iso: "NE",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ne.svg",
		mask: "__-__-____",
	},
	{
		name: "Nigeria",
		code: "+234",
		iso: "NG",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ng.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Niue",
		code: "+683",
		iso: "NU",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/nu.svg",
		mask: "____",
	},
	{
		name: "Norfolk Island",
		code: "+672",
		iso: "NF",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/nf.svg",
		mask: "___-___",
	},
	{
		name: "North Macedonia",
		code: "+389",
		iso: "MK",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mk.svg",
		mask: "__-___-___",
	},
	{
		name: "Northern Mariana Islands",
		code: "+1",
		iso: "MP",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mp.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Norway",
		code: "+47",
		iso: "NO",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/no.svg",
		mask: "(___) __-___",
	},
	{
		name: "Oman",
		code: "+968",
		iso: "OM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/om.svg",
		mask: "__-___-___",
	},
	{
		name: "Pakistan",
		code: "+92",
		iso: "PK",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/pk.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Palau",
		code: "+680",
		iso: "PW",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/pw.svg",
		mask: "___-____",
	},
	{
		name: "Palestine",
		code: "+970",
		iso: "PS",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ps.svg",
		mask: "__-___-____",
	},
	{
		name: "Panama",
		code: "+507",
		iso: "PA",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/pa.svg",
		mask: "___-____",
	},
	{
		name: "Papua New Guinea",
		code: "+675",
		iso: "PG",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/pg.svg",
		mask: "(___) __-___",
	},
	{
		name: "Paraguay",
		code: "+595",
		iso: "PY",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/py.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Peru",
		code: "+51",
		iso: "PE",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/pe.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Philippines",
		code: "+63",
		iso: "PH",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ph.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Pitcairn",
		code: "+870",
		iso: "PN",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/pn.svg",
		mask: "___-___-___",
	},
	{
		name: "Poland",
		code: "+48",
		iso: "PL",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/pl.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Portugal",
		code: "+351",
		iso: "PT",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/pt.svg",
		mask: "__-___-____",
	},
	{
		name: "Puerto Rico",
		code: "+1",
		iso: "PR",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/pr.svg",
		mask: "(___) ___ ____",
	},
	{
		name: "Qatar",
		code: "+974",
		iso: "QA",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/qa.svg",
		mask: "____-____",
	},
	{
		name: "Reunion",
		code: "+262",
		iso: "RE",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/re.svg",
		mask: "_____-____",
	},
	{
		name: "Romania",
		code: "+40",
		iso: "RO",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ro.svg",
		mask: "__-___-____",
	},
	{
		name: "Russia",
		code: "+7",
		iso: "RU",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ru.svg",
		mask: "(___) ___-__-__",
	},
	{
		name: "Rwanda",
		code: "+250",
		iso: "RW",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/rw.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Saint Barthelemy",
		code: "+590",
		iso: "BL",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/bl.svg",
		mask: "___-__-__-__",
	},
	{
		name: "Saint Helena, Ascension and Tristan Da Cunha",
		code: "+290",
		iso: "SH",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sh.svg",
		mask: "____",
	},
	{
		name: "Saint Kitts and Nevis",
		code: "+1",
		iso: "KN",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/kn.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Saint Lucia",
		code: "+1",
		iso: "LC",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/lc.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Saint Martin",
		code: "+590",
		iso: "MF",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/mf.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Saint Pierre and Miquelon",
		code: "+508",
		iso: "PM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/pm.svg",
		mask: "__-____",
	},
	{
		name: "Saint Vincent and the Grenadines",
		code: "+1",
		iso: "VC",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/vc.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Samoa",
		code: "+685",
		iso: "WS",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ws.svg",
		mask: "__-____",
	},
	{
		name: "San Marino",
		code: "+378",
		iso: "SM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sm.svg",
		mask: "____-______",
	},
	{
		name: "Sao Tome and Principe",
		code: "+239",
		iso: "ST",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/st.svg",
		mask: "__-_____",
	},
	{
		name: "Saudi Arabia",
		code: "+966",
		iso: "SA",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sa.svg",
		mask: "_-____-____",
	},
	{
		name: "Senegal",
		code: "+221",
		iso: "SN",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sn.svg",
		mask: "__-___-____",
	},
	{
		name: "Serbia",
		code: "+381",
		iso: "RS",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/rs.svg",
		mask: "__-___-____",
	},
	{
		name: "Seychelles",
		code: "+248",
		iso: "SC",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sc.svg",
		mask: "_-___-___",
	},
	{
		name: "Sierra Leone",
		code: "+232",
		iso: "SL",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sl.svg",
		mask: "__-______",
	},
	{
		name: "Singapore",
		code: "+65",
		iso: "SG",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sg.svg",
		mask: "____-____",
	},
	{
		name: "Sint Maarten",
		code: "+1",
		iso: "SX",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sx.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Slovakia",
		code: "+421",
		iso: "SK",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sk.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Slovenia",
		code: "+386",
		iso: "SI",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/si.svg",
		mask: "__-___-___",
	},
	{
		name: "Solomon Islands",
		code: "+677",
		iso: "SB",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sb.svg",
		mask: "___-____",
	},
	{
		name: "Somalia",
		code: "+252",
		iso: "SO",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/so.svg",
		mask: "__-___-___",
	},
	{
		name: "South Africa",
		code: "+27",
		iso: "ZA",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/za.svg",
		mask: "__-___-____",
	},
	{
		name: "South Georgia and the South Sandwich Islands",
		code: "+500",
		iso: "GS",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gs.svg",
		mask: "_____",
	},
	{
		name: "South Sudan",
		code: "+211",
		iso: "SS",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ss.svg",
		mask: "__-___-____",
	},
	{
		name: "Spain",
		code: "+34",
		iso: "ES",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/es.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Sri Lanka",
		code: "+94",
		iso: "LK",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/lk.svg",
		mask: "__-___-____",
	},
	{
		name: "Sudan",
		code: "+249",
		iso: "SD",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sd.svg",
		mask: "__-___-____",
	},
	{
		name: "Suriname",
		code: "+597",
		iso: "SR",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sr.svg",
		mask: "___-____",
	},
	{
		name: "Svalbard and Jan Mayen",
		code: "+47",
		iso: "SJ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sj.svg",
		mask: "(___) __-___",
	},
	{
		name: "Sweden",
		code: "+46",
		iso: "SE",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/se.svg",
		mask: "__-___-____",
	},
	{
		name: "Switzerland",
		code: "+41",
		iso: "CH",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ch.svg",
		mask: "__-___-____",
	},
	{
		name: "Syrian Arab Republic",
		code: "+963",
		iso: "SY",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/sy.svg",
		mask: "__-____-___",
	},
	{
		name: "Taiwan",
		code: "+886",
		iso: "TW",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/tw.svg",
		mask: "_-____-____",
	},
	{
		name: "Tajikistan",
		code: "+992",
		iso: "TJ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/tj.svg",
		mask: "__-___-____",
	},
	{
		name: "United Republic of Tanzania",
		code: "+255",
		iso: "TZ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/tz.svg",
		mask: "__-___-____",
	},
	{
		name: "Thailand",
		code: "+66",
		iso: "TH",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/th.svg",
		mask: "__-___-____",
	},
	{
		name: "Timor-Leste",
		code: "+670",
		iso: "TL",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/tl.svg",
		mask: "___-_____",
	},
	{
		name: "Togo",
		code: "+228",
		iso: "TG",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/tg.svg",
		mask: "__-___-___",
	},
	{
		name: "Tokelau",
		code: "+690",
		iso: "TK",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/tk.svg",
		mask: "____",
	},
	{
		name: "Tonga",
		code: "+676",
		iso: "TO",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/to.svg",
		mask: "_____",
	},
	{
		name: "Trinidad and Tobago",
		code: "+1",
		iso: "TT",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/tt.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Tunisia",
		code: "+216",
		iso: "TN",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/tn.svg",
		mask: "__-___-___",
	},
	{
		name: "Turkey",
		code: "+90",
		iso: "TR",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/tr.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Turkmenistan",
		code: "+993",
		iso: "TM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/tm.svg",
		mask: "_-___-____",
	},
	{
		name: "Turks and Caicos Islands",
		code: "+1",
		iso: "TC",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/tc.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Tuvalu",
		code: "+688",
		iso: "TV",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/tv.svg",
		mask: "______",
	},
	{
		name: "Uganda",
		code: "+256",
		iso: "UG",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ug.svg",
		mask: "(___) ___-___",
	},
	{
		name: "Ukraine",
		code: "+380",
		iso: "UA",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ua.svg",
		mask: "(__) ___-__-__",
	},
	{
		name: "United Arab Emirates",
		code: "+971",
		iso: "AE",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ae.svg",
		mask: "_-___-____",
	},
	{
		name: "United Kingdom",
		code: "+44",
		iso: "GB",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/gb.svg",
		mask: "__-____-____",
	},
	{
		name: "United States",
		code: "+1",
		iso: "US",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/us.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Uruguay",
		code: "+598",
		iso: "UY",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/uy.svg",
		mask: "_-___-__-__",
	},
	{
		name: "Uzbekistan",
		code: "+998",
		iso: "UZ",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/uz.svg",
		mask: "__-___-____",
	},
	{
		name: "Vanuatu",
		code: "+678",
		iso: "VU",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/vu.svg",
		mask: "__-_____",
	},
	{
		name: "Venezuela, Bolivarian Republic of Venezuela",
		code: "+58",
		iso: "VE",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ve.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Vietnam",
		code: "+84",
		iso: "VN",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/vn.svg",
		mask: "(___) ____-___",
	},
	{
		name: "Virgin Islands, British",
		code: "+1",
		iso: "VG",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/vg.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Virgin Islands, U.S.",
		code: "+1",
		iso: "VI",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/vi.svg",
		mask: "(___) ___-____",
	},
	{
		name: "Wallis and Futuna",
		code: "+681",
		iso: "WF",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/wf.svg",
		mask: "__-____",
	},
	{
		name: "Yemen",
		code: "+967",
		iso: "YE",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/ye.svg",
		mask: "___-___-___",
	},
	{
		name: "Zambia",
		code: "+260",
		iso: "ZM",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/zm.svg",
		mask: "__-___-____",
	},
	{
		name: "Zimbabwe",
		code: "+263",
		iso: "ZW",
		flag: "https://cdn.kcak11.com/CountryFlags/countries/zw.svg",
		mask: "_-______",
	},
] as const;

export { type CountryType, countries };
