import { index, type RouteConfig, route } from "@react-router/dev/routes";

export default [
	index("./_index.tsx"),
	route("/alert", "./components/components.alert.tsx"),
	route("/audio-player", "./components/components.audioPlayer.tsx"),
	route("/audio-upload", "./components/components.audioUpload.tsx"),
	route("/badge", "./components/components.badge.tsx"),
	route("/button", "./components/components.button.tsx"),
	route("/calendar", "./components/components.calendar.tsx"),
	route("/card-tab", "./components/components.cardTab.tsx"),
	route("/checkbox", "./components/components.checkbox.tsx"),
	route("/client-only", "./components/components.clientOnly.tsx"),
	route("/currency-input", "./components/components.currencyInput.tsx"),
	route("/divider", "./components/components.divider.tsx"),
	route("/drawer", "./components/components.drawer.tsx"),
	route("/file-upload", "./components/components.fileUpload.tsx"),
	route("/full-calendar", "./components/components.fullCalendar.tsx"),
	route("/icon-button", "./components/components.iconButton.tsx"),
	route("/image-upload", "./components/components.imageUpload.tsx"),
	route("/input", "./components/components.input.tsx"),
	route("/masked-input", "./components/components.maskedInput.tsx"),
	route("/modal", "./components/components.modal.tsx"),
	route("/multi-select", "./components/components.multiSelect.tsx"),
	route("/pagination", "./components/components.pagination.tsx"),
	route("/phone-input", "./components/components.phoneInput.tsx"),
	route("/popover", "./components/components.popover.tsx"),
	route("/radio-group", "./components/components.radioGroup.tsx"),
	route("/rich-text", "./components/components.richText.tsx"),
	route("/select", "./components/components.select.tsx"),
	route("/slider", "./components/components.slider.tsx"),
	route("/switch", "./components/components.switch.tsx"),
	route("/tab", "./components/components.tab.tsx"),
	route("/table", "./components/components.table.tsx"),
	route("/textarea", "./components/components.textarea.tsx"),
	route("/tooltip", "./components/components.tooltip.tsx"),
] satisfies RouteConfig;
